title: Zoe Swash 
author: Zoe Vekselstein
email: artem.z@takeoff.com
description: > # this means to ignore newlines until "baseurl:"
  I decided to venture on something bigger...

# social links
twitter_username: no-twitter # DO NOT include the @ character, or else the build will fail!
github_username:  azhuchenko # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
